services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: belajar_db
      MYSQL_USER: michael
      MYSQL_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"

volumes:
  mysql-data: {}
